### ISSUE TITLE
bealign error

### ISSUE THREAD

**Issue by rdvelazquez** [rdvelazquez/tools-iuc#1]
@stevenweaver,

This is probably just user error but I figured I'd post where I'm at with trying out bealign on galaxy.hyphy.org to see if you have any input. I'm using the fasta file from the HIV-TRACE testing folder (https://github.com/veg/hivtrace/tree/master/test/rsrc) and the HXB2_tat internal reference for the input alignment.

![bealign error](https://user-images.githubusercontent.com/25244432/36549311-7d64fdcc-17c0-11e8-9431-4ce2ae55d6a1.gif)

Also tagging @stephenshank for his reference.

**Comment by stevenweaver** [comment]
Dear @rdvelazquez, 

Please try `HXB2_prrt` as the reference. 

Best,
Steven

**Comment by rdvelazquez** [comment]
Unfortunately, I'm still getting the same error when using `HXB2_prrt` as the reference.

The stderr that I've gotten both times is: 
`Fatal error: Exit code 127 ()
/home/galaxy/galaxy/database/jobs_directory/000/17/tool_script.sh: line 9: bealign: command not found`

**Comment by stevenweaver** [comment]
Dear @rdvelazquez,

It might have to do with this bug https://github.com/veg/BioExt/issues/20 <https://github.com/veg/BioExt/issues/20>

Best,
Steven

**Comment by rdvelazquez** [comment]
This was a configuration error on our end.
